# See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# and https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-nodejs :
---
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3 # https://github.com/azure/setup-helm
        with:
          version: v3.12.2
      - name: Package and index Helm chart
        run: |
          set -o errexit -o nounset -o pipefail
          helm package . --destination dist
          curl --fail --output-dir dist --remote-name --silent https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml
          helm repo index dist --merge dist/index.yaml --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
      - name: Publish Helm repository
        uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: dist
name: Release Charts
on:
  push:
    # Publish semver tags as releases:
    tags: [ 'v*.*.*' ]
